CREATE TABLE `target_id13` (
  `gravity_pk` varchar(48) CHARACTER SET utf8 NOT NULL,
  `bdl_id` varchar(1) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_pat_no` int(5) DEFAULT NULL,
  `bdl_ipd_no` varchar(11) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_in_dt` varchar(7) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_in_ti` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_in_dt_v` varchar(7) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_in_ti_v` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_bed` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_dpt` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_dr1` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_dr2` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_rd_dr` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_cla` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_old_bed` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_old_dpt` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_old_dr1` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_old_dr2` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_old_rd` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_old_cla` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_old_dt` varchar(7) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_old_time` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_upd_code` varchar(1) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_upd_dt` varchar(7) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_upd_ti` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_upd_uid` varchar(5) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_abn_uid` varchar(5) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_sel_grd` varchar(2) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_assist_uid` varchar(5) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_vir_mod_dt` varchar(7) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_vir_mod_ti` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_vir_bed` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `bdl_vir_mod_uid` varchar(5) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`gravity_pk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

