apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gravity2-lab
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: gitea
        - containerPort: 22
          name: git-ssh
        volumeMounts:
        - mountPath: /var/lib/gitea
          name: git-volume
        - mountPath: /etc/gitea
          name: git-volume1
      volumes:
      - name: git-volume
        persistentVolumeClaim:
          claimName: git-volume
      - name: git-volume1
        persistentVolumeClaim:
          claimName: git-volume1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-volume
  namespace: gravity2-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  #storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-volume1
  namespace: gravity2-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  #storageClassName: standard

---

apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gravity2-lab
spec:
  ports:
  - name: client
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31300
  selector:
    app: gitea
  type: NodePort
