apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: target3-postgres-volume
  namespace: gravity2-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  #storageClassName: standard

---

apiVersion: v1
kind: Service
metadata:
  name: target3-postgres
  namespace: gravity2-lab
  labels:
    app: gravity
spec:
  ports:
    - port: 5432
      name: tcp
      protocol: TCP
      nodePort: 30432
  selector:
    name: target3-postgres
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: target3-postgres
  namespace: gravity2-lab
  labels:
    name: target3-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: target3-postgres
  template:
    metadata:
      labels:
        name: target3-postgres
    spec:
      hostname: target3-postgres
      securityContext: {}
      containers:
        - image: postgres:16.4-bookworm
          name: target3-postgres
          env:
            - name: "POSTGRES_DB"
              value: "testdb"
            - name: "POSTGRES_USER"
              value: "postgres"
            - name: "POSTGRES_PASSWORD"
              value: "1qaz@WSX"
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data-store
          ports:
            - containerPort: 5432
              name: tcp
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: target3-postgres-volume
